# Файл docker-compose.yml

# Версия docker-compose:
#version: '3'

# Перечень volume:
volumes:
  pg_data:
  static:
  media:

# Перечень контейнеров:
services:
  # Имя и описание первого контейнера; имя выбирает разработчик. 
  # Это контейнер с базой данных:
  postgres:
    container_name: postgres
    # Из какого образа запустить контейнер:
    image: postgres:13.10
    # Файл (или список файлов) с переменными окружения:
    env_file: .env
    # Какой volume подключить для этого контейнера:
    volumes:
      - pg_data:/var/lib/postgresql/data
    networks:
      - kittygram_network
  # Имя и описание контейнера с бэкендом:
  backend:
    container_name: backend
    # Из какого Dockerfile собирать образ для этого контейнера:
    env_file: .env
    # Какие контейнеры нужно запустить до старта этого контейнера:
    depends_on:
      - postgres
    volumes:
      - static:/app/collected_static
      - media:/app/media
    networks:
      - kittygram_network
  frontend:
    container_name: frontend
    env_file: .env
    volumes:
      #- static:/static
      - static:/app/build
    networks:
      - kittygram_network
  
  # Контейнер с Nginx (gateway):
  gateway:
    container_name: gateway
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/site.conf:/etc/nginx/conf.d/default.conf
      #- static:/static
      - static:/usr/share/nginx/html
      - media:/var/www/media
    ports:
      - "80:80"
    networks:
      - kittygram_network

networks:
  kittygram_network:
    external: false
