name: Test Docker Login

on: [push]

jobs:
  test-login:
    runs-on: ubuntu-latest
    steps:
      - name: Login to Docker
        uses: docker/login-action@v2.2.0
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
